# Project: EternalMist
# Makefile created by Dev-C++ 4.9.9.2

CPP  = g++.exe
CC   = gcc.exe
WINDRES = windres.exe
RES  = 
OBJ  = main.o $(RES)
LINKOBJ  = main.o $(RES)
LIBS =  -L"lib" -mwindows ../../../../../../Dev-Cpp/lib/liballeg.a  
INCS =  -I"include"  -I"C:/Users/Utter/Documents/GitHub/rpg_game/EternalMist" 
CXXINCS =  -I"lib/gcc/mingw32/3.4.2/include"  -I"include/c++/3.4.2/backward"  -I"include/c++/3.4.2/mingw32"  -I"include/c++/3.4.2"  -I"include"  -I"C:/Users/Utter/Documents/GitHub/rpg_game/EternalMist" 
BIN  = EternalMist.exe
CXXFLAGS = $(CXXINCS)   -fexpensive-optimizations
CFLAGS = $(INCS)   -fexpensive-optimizations
RM = rm -f

.PHONY: all all-before all-after clean clean-custom

all: all-before EternalMist.exe all-after


clean: clean-custom
	${RM} $(OBJ) $(BIN)

$(BIN): $(OBJ)
	$(CPP) $(LINKOBJ) -o "EternalMist.exe" $(LIBS)

main.o: main.cpp   C:/Users/Utter/Documents/GitHub/rpg_game/EternalMist/main.h   C:/Users/Utter/Documents/GitHub/rpg_game/EternalMist/world.h   C:/Users/Utter/Documents/GitHub/rpg_game/EternalMist/graphics.h   C:/Users/Utter/Documents/GitHub/rpg_game/EternalMist/actors.h   C:/Users/Utter/Documents/GitHub/rpg_game/EternalMist/areas.h   C:/Users/Utter/Documents/GitHub/rpg_game/EternalMist/objects.h
	$(CPP) -c main.cpp -o main.o $(CXXFLAGS)
